spring:
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  boot:
    admin:
      context-path: /admin
server:
  compression:
    enabled: true
    mime-types: application/json
auth:
  scopes:
    - user:read
    - user:write
