spring:
  profiles:
    active: dev
  messages:
    basename: i18n/messages
server:
  compression:
    enabled: true
    mime-types: application/json
firebase:
  service-account-key-name: yolooapp-dev-firebase-adminsdk.json
  database-url: https://yolooapp-dev.firebaseio.com

---

spring:
  profiles: dev
  cloud:
    gcp:
      pubsub:
        emulator-host: http://localhost:8085
debug: false

---

spring:
  profiles: staging

---

spring:
  profiles: prod