spring:
  profiles:
    active: dev
firebase:
  service-account-key-name: yolooapp-dev-firebase-adminsdk.json
  database-url: https://yolooapp-dev.firebaseio.com
yoloo:
  notification:
    scheduler:
      fixed-rate: 5000
      initial-delay: 5000

---

spring:
  profiles: dev
  cloud:
    gcp:
      pubsub:
        emulator-host: localhost:8085
debug: false

---

spring:
  profiles: staging

---

spring:
  profiles: prod