spring:
  profiles:
    active: dev
firebase:
  service-account-key-name: yolooapp-dev-firebase-adminsdk.json
  database-url: https://yolooapp-dev.firebaseio.com

---

spring:
  profiles: dev
  cloud:
    gcp:
      pubsub:
        emulator-host: localhost:8085
debug: false

---

spring:
  profiles: staging

---

spring:
  profiles: prod